

name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
    paths:
      - 'Frontend_app/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend_app/frontend_app

    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSTANT_FORM_475413_N8 }}
          channelId: live
          projectId: ${{ secrets.GCP_PROJECT_ID }}


